---
version: '3'
 
services:
  packet_raptor:
    image: johncapobianco/packet_raptor:packet_raptor
    container_name: packet_raptor
    restart: always
    build: 
      context: ./
      dockerfile: ./docker/Dockerfile   
    ports:
      - "8585:8585"     
    volumes:
      - ./config.toml:/root/.streamlit/config.toml
